name: Deploy PDF

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile LaTeX document
      uses: xu-cheng/texlive-action@v2
      with:
        scheme: full
        run: |
          apk add make sed
          make document

    - name: List directory
      run: |
        ls -lhtra

    - name: Upload pdf
      uses: actions/upload-artifact@v4
      with:
        name: proceedings
        path: 'chep_2023_proceedings.pdf'

    - name: Build arXiv archive
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      uses: xu-cheng/texlive-action@v2
      with:
        scheme: full
        run: |
          apk add make sed
          make arXiv

    - name: Unpack archive
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      run: |
        tar -xzvf submit_to_arXiv.tar.gz

    - name: Upload arXiv archive
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: submit_to_arXiv
        path: 'submit_to_arXiv'

  deploy:

    name: Deploy GitHub Pages
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Create site directory structure
      run: |
        mkdir -p _site/
        touch _site/index.html
        touch _site/.nojekyll

    - uses: actions/download-artifact@v4
      with:
        name: proceedings
        path: '_site/'

    - name: Check site structure
      run: |
        tree _site

    - name: Fix permissions
      run: |
        chmod -c -R +rX "_site/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
